
logger:
  level: WARN
  baud_rate: 0
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"

  # Enables mDNS Service
mdns:
  disabled: false

  #  Enables the local webserver on the ESP device, upon port 80
web_server:
  port: 80

#network:
#  enable_ipv6: false